### PR TITLE
Provide flag to exclude `.Notes` section from ProxyCmdletDefinitions.ps1

### PR DESCRIPTION
**Pull request by georgend**
Provide flag `-ExcludeNoteSection` to control writing of `.Notes` section into `ProxyCmdletDefinitions.ps1`.
Refer user to use `Get-Help -Online`.
This reduce module bloat.
image

cc. @maisarissi, @peombwa, @shemogumbe

### CODE REVIEW

**Comment by maisarissi** [comment]
Hi @dolauli, @georgend opened this new PR following your instructions.
Can you please review the changes?
Thanks!

**Review by dolauli — APPROVED** [review]
LGTM

**Comment by georgend** [comment]
@dolauli Thanks for the review. 
Unfortunately I don't have merge permissions on this repository.

**Comment by dolauli** [comment]
@georgend I have merged the other PR. And this one has conflict with it. Please resolve the conflicts.

**Comment by georgend** [comment]
The original branch was deleted in my fork, so I have issued a new PR.

**Pull request closed without merging**
