### PR TITLE
renamed name of OperationParameter to avoid collision

### PR DESCRIPTION
**Pull request by joshspicer**
Perhaps a better solution as it is a single change in the super class.  Related to #390 .

### CODE REVIEW

**Comment by fearthecowboy** [comment]
Ah, I see what you're looking to fix; it wasn't clicking for me before.

I think it's better to rename the `identity` parameter to something -- in this case the emitted name will change, but the model behind it doesn't so if we are trying to match cosmetically later, it won't.

I'll change the `identity` to `viaIdentity` (the TS local variable name doesn't need to change)

just pushed this; https://github.com/Azure/autorest.powershell/commit/4f317df6d596a766fb076acc95fa898b997e9210#diff-3ae15e21bfc8b038bc04267167e69d0bR56

That does make me think that I should really tag that with a UID and match it, but that's a task for another day.

**Comment by kenal-microsoft** [comment]
Renaming the identity parameter certainly fixes the immediate issue – that an internal parameter is named identity and our REST parameter is also named identity and they both can’t exist in the same scope.

The risk here is that naming it viaIdentity opens the possibility (however unlikely) that someone could come along with a swagger that has a parameter called “viaIdentity” and the same collision happens. It still relies on everybody else avoiding a special name.

If we prefix all the named parameters from Swagger, then it’s literally impossible for them to collide with an internal parameter, because the internal parameter would have to start with the prefix, and that’s under our control.

**Comment by fearthecowboy** [comment]
resolved elseweher

**Pull request closed without merging**
