### PR TITLE
Exclude Examples Scenario

### PR DESCRIPTION
**Pull request by georgend**
Enable a scenario where Examples should not be produced and embedded in ProxyCmdlets. 
The generated example stubs may not be suitable for teams where examples are not available yet. 

cc. @peombwa

### CODE REVIEW

**Comment by dolauli** [comment]
Considering it is a temp requirement special for Graph, I suggest you could build a package locally instead of doing a release in github. After the build, you may follow steps blew to package, install and use the local built version.

1. Change the package version to 3.0.x, let's say 3.0.0 in powershell/package.json.
2. package with following command
`npx @microsoft/rush publish --publish --pack --include-all --tag latest`
3. Install the package (you should find it in common/temp/artifacts/packages and if there are other versions of autorest/powershell in your machine, run 'autorest --reset' first)
`npm install --prefix ~/.autorest/@autorest_powershell@3.0.0 autorest-powershell-3.0.0.tgz`
4. Code gen with the local built version
`autorest `

**Comment by finsharp** [comment]
@dolauli We will be executing this in a pipeline, it would have been ideal to have a release.

**Comment by dolauli** [comment]
> @dolauli We will be executing this in a pipeline, it would have been ideal to have a release.
> Using a local version would mean forking, and keeping the fork upto date over time.

@finsharp This change is special for Graph, so I would not include it a public release. An alternative is you could put the local built package in a web site (github or blob store). And then you could follow the example below to use it. And ideally, you may convert the long url to a short one through https://tinyurl.com/.
`autorest --use:https://github.com/Azure/autorest.powershell/releases/download/v2.1.402/autorest-powershell-2.1.402.tgz`

**Comment by darrelmiller** [comment]
@dolauli  This is not a Graph specific request, nor is it a temporary request.  The Autorest PowerShell generator takes an OpenAPI document and generates PowerShell cmdlets and does a best effort at generating documentation based on the information in the OpenAPI description.  The AutoREST PowerShell generator does not attempt to take examples from the OpenAPI and generate code examples.  It requires manual intervention to fill out the examples.   Filling out the examples should be optional, just like all the other customizations are option.  We should not produce documentation that has placeholder text that says "examples go here" as that is unprofessional and makes the commandlets unfinished.

We are currently struggling with the size of the PowerShell commandlets generated by AutoREST and the last thing we need is even more bulk to our packages.  We also have another place in our reference documentation where we show code snippets for examples in all of our supported languages.  That will be the primary place that users will find code examples.  We may chose to never include examples in our embedded docs pages.

**Pull request closed without merging**
